import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/component/Authprovider/Authprovider";
import { GoogleButtonProvider } from "@/contexts/googleContext";
import { DropdownProvider } from "@/contexts/DropdownRendering";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <DropdownProvider>
            <GoogleButtonProvider>{children}</GoogleButtonProvider>
          </DropdownProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
